version: "3.8"

services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
            - SUPABASE_URL=${SUPABASE_URL}
            - SUPABASE_KEY=${SUPABASE_KEY}
            - SECRET_KEY=${SECRET_KEY}
        depends_on:
            - db

    db:
        image: postgres:13
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
